-- This file is generated by program!
-- Don't change it manaully.
-- Author: hankangwen@qq.com  Kerven
-- Source file: Config/ConfigAll.lua
-- Created at: Jul 2022



--load require管理名称--
local LoadRq =
{
	 Hero = require "Config/Hero",
	 HeroName = require "Config/HeroName",
	 Item = require "Config/Item",
	 ItemShop = require "Config/ItemShop",
}

--配置管理名称--
ConfigName =
{
	Hero = "Hero",
	HeroName = "HeroName",
	Item = "Item",
	ItemShop = "ItemShop",
}

--配置文件管理--
ConfigAll = {};
local this = ConfigAll;
local configList = {};

--添加所有配置到管理列表--
function ConfigAll.LoadAll()
	   this.AddConfig(ConfigName.Hero, LoadRq.Hero);
	   this.AddConfig(ConfigName.HeroName, LoadRq.HeroName);
	   this.AddConfig(ConfigName.Item, LoadRq.Item);
	   this.AddConfig(ConfigName.ItemShop, LoadRq.ItemShop);
end

--添加配置表--
function ConfigAll.AddConfig(configName, configObj)
	configList[configName] = configObj;
end

--获取配置表--
function ConfigAll.GetConfig(configName)
	return configList[configName];
end

--移除配置表--
function ConfigAll.RemoveConfig(configName)
	configList[configName] = nil;
end

return ConfigAll;
